### ISSUE TITLE
SimpleITK error when running the nnUNet extension inference 

### ISSUE THREAD

**Issue by mazensoufi** [KitwareMedical/SlicerNNUnet#6]
Hi,
I'm running the nnUNet extension with a locally trained model.
My Slicer version is Slicer 5.7.0-2024-06-04
The installed nnUNet version is 2.4.2
nnUNet Run Settings are shown here
![image](https://github.com/KitwareMedical/SlicerNNUnet/assets/31057519/45a0fcc3-ff8d-4b5e-8ce7-65d2bf136513)

The nnUNet module starts running, but stops after the preprocessing step as shown below:
```

nnUNet preprocessing...
Traceback (most recent call last):
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Scripts\nnUNetv2_predict.exe\__main__.py", line 4, in <module>
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 22, in <module>
    from nnunetv2.inference.data_iterators import PreprocessAdapterFromNpy, preprocessing_iterator_fromfiles, \
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\inference\data_iterators.py", line 12, in <module>
    from nnunetv2.preprocessing.preprocessors.default_preprocessor import DefaultPreprocessor
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\preprocessing\preprocessors\default_preprocessor.py", line 29, in <module>
    from nnunetv2.utilities.plans_handling.plans_handler import PlansManager, ConfigurationManager
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py", line 16, in <module>
    from nnunetv2.imageio.reader_writer_registry import recursive_find_reader_writer_by_name
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\imageio\reader_writer_registry.py", line 9, in <module>
    from nnunetv2.imageio.simpleitk_reader_writer import SimpleITKIO
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\nnunetv2\imageio\simpleitk_reader_writer.py", line 19, in <module>
    import SimpleITK as sitk
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\SimpleITK\__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-06-04\lib\Python\Lib\site-packages\SimpleITK\SimpleITK.py", line 16, in <module>
    from . import _SimpleITK
ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.
Loading inference results...
Inference ended in error:
Failed to load the segmentation.
```

Tried to check similar issues, but all are reporting SimpleITK building solutions.
Any solution for this?

Thanks for your help in advance,,

**Comment by MathijsdeBoer** [comment]
My current workaround is to use a previous version of 5.7.0. The build from 2024-06-08 seems to have a bug with its SimpleITK install, the 2024-05-31 build works. Though, I have not tested any of the builds in between, so one of those might still work, too

https://download.slicer.org/?closest-revision=32881

**Comment by mazensoufi** [comment]
@MathijsdeBoer Thanks a lot for your reply.
I reinstalled the previous version, and the SimpleITK issue was solved! 
However, the inference could not proceed with the following error issued after starting the preprocessing,

```
nnUNet preprocessing...
C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py:37: UserWarning: Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.
  warnings.warn("Detected old nnU-Net plans format. Attempting to reconstruct network architecture "
Traceback (most recent call last):
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Scripts\nnUNetv2_predict.exe\__main__.py", line 7, in <module>
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 859, in predict_entry_point
    predictor.initialize_from_trained_model_folder(
  File "C:\Users\msoufi\AppData\Local\slicer.org\Slicer 5.7.0-2024-05-30\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 100, in initialize_from_trained_model_folder
    network = trainer_class.build_network_architecture(
AttributeError: 'NoneType' object has no attribute 'build_network_architecture'

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################
Loading inference results...
Inference ended in error:
Failed to load the segmentation.
Check the inference folder content C:\Users\msoufi\AppData\Local\Temp\Slicer-uXpiFb\output

```

Could you provide the required nnUNet release for training the custom models?

Thanks again for your help,,

**Comment by MathijsdeBoer** [comment]
I'm just using the latest nnUNet version, 2.4.0.

**Comment by mazensoufi** [comment]
@MathijsdeBoer 
Thanks a lot. I found the issue. The trainer name is used in the inference pipeline to set the inference model path. 
Since I'm using a custom trainer (variant epochs), I had to add its class to the file below in order to be recognized.
`Slicer 5.7.0-2024-05-30\lib\Python\Lib\site-packages\nnunetv2\training\nnUNetTrainer\variants\training_length\nnUNetTrainer_Xepochs.py
`
and now it works well.

Thanks again!

**Comment by Thibault-Pelletier** [comment]
@mazensoufi  and @MathijsdeBoer  thank you for opening / following up on this issue.

Regarding the original SimpleITK problem, this is a problem related to Slicer directly on Windows system. 
See the opened issue here : https://github.com/Slicer/Slicer/issues/7799

This should be solved in coming 3D Slicer versions.
